exercises: space-age: fix compilation errors (#106)
This may not be the best fix. But, along with the update to Zig 0.8.1,
these changes do at least make the tests pass for every exercise.

Before this commit:

    $ zig test test_space_age.zig
    /usr/lib/zig/std/testing.zig:263:27: error: Cannot approximately compare two comptime_float values
            .ComptimeFloat => @compileError("Cannot approximately compare two comptime_float values"),
                              ^
    ./exercises/practice/space-age/test_space_age.zig:10:43: note: called from here
        comptime try testing.expectApproxEqRel(expected, actual, 1.0);
                                              ^
    ./exercises/practice/space-age/test_space_age.zig:6:21: note: called from here
    test "age on earth" {
                        ^

With this commit:

    $ zig test test_space_age.zig
    All 8 tests passed.

Closes: #104