proverb, rna-transcription, secret-handshake: fix mem.Allocator usage
Upgrading Zig from version 0.8.1 to 0.9.1 produced errors like:

    ./test_proverb.zig:12:46: error: expected type '*std.mem.Allocator', found 'std.mem.Allocator'
        const actual = try proverb.recite(testing.allocator, input_slice);
                                                 ^
    /foo/zig-linux-x86_64-0.9.1/lib/std/mem/Allocator.zig:1:1: note: std.mem.Allocator declared here
    //! The standard memory allocation interface.
    ^

Fix the errors by following the advice from the Zig 0.9.0 release
notes [1]:

    The `mem.Allocator` interface has changed in a breaking way.

    In short summary, here is how to change your code:

    - Change `*Allocator` to `Allocator` in function parameter types and
      struct field types.

    - Instead of taking the pointer to an allocator field, such as
      `&gpa.allocator`, use a function call like this: `gpa.allocator()`.

For more details, see the blog post on Allocgate [2].

[1] https://ziglang.org/download/0.9.0/release-notes.html#Allocgate
[2] https://pithlessly.github.io/allocgate.html