exercises: stubs: use compileError, not panic (#196)
Before this commit, when running the tests for an exercise with a
stub that used `@panic`, we might see something like:

    $ zig test test_leap.zig
    Test [1/9] test.year not divisible by 4 in common year... thread 123456 panic: please implement the isLeapYear function
    /foo/exercism-tracks/zig/exercises/practice/leap/leap.zig:3:5: 0x20aaaa in isLeapYear (test)
        @panic("please implement the isLeapYear function");
        ^
    /foo/exercism-tracks/zig/exercises/practice/leap/test_leap.zig:7:40: 0x20bbbb in test.year not divisible by 4 in common year (test)
        try testing.expect(!leap.isLeapYear(2015));
                                           ^
    /usr/lib/zig/lib/test_runner.zig:66:28: 0x20cccc in main (test)
            } else test_fn.func();
                               ^
    /usr/lib/zig/lib/std/start.zig:606:22: 0x20dddd in posixCallMainAndExit (test)
                root.main();
                         ^
    /usr/lib/zig/lib/std/start.zig:376:5: 0x20eeee in _start (test)
        @call(.never_inline, posixCallMainAndExit, .{});
        ^
    error: the following test command crashed:
    /foo/.cache/zig/o/01234567890123456789012345678901/test

With this commit:

    $ zig test test_leap.zig
    leap.zig:3:5: error: please implement the isLeapYear function
        @compileError("please implement the isLeapYear function");
        ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    referenced by:
        test.year divisible by 200, not divisible by 400 in common year: test_leap.zig:39:29
        remaining reference traces hidden; use '-freference-trace' to see all reference traces

Also fix a typo in the resistor-color-duo stub.

Closes: #176