exercises: stubs: resolve unused parameter errors
Before this commit, when testing an unchanged exercise stub:

    $ zig test test_leap.zig
    leap.zig:1:19: error: unused function parameter
    pub fn isLeapYear(year: u32) bool {
                      ^~~~

With this commit:

    $ zig test test_leap.zig
    Test [1/9] test.year not divisible by 4 in common year... thread 123456 panic: please implement the isLeapYear function
    /foo/exercism-tracks/zig/exercises/practice/leap/leap.zig:3:5: 0x201234 in isLeapYear (test)
        @panic("please implement the isLeapYear function");
    [...]

Closes: #175