exercises(leap): example: fix for Zig 0.10.1
Simplify the example solution, for which Zig 0.10.1 produced an error:

    $ zig test test_leap.zig
    leap.zig:8:21: error: no field named 'has_factor' in struct 'leap.leap__struct_1016'
        }{ .y = year }).has_factor;
                    ^~~~~~~~~~
    leap.zig:2:25: note: struct declared here
        const has_factor = (struct {
                        ^~~~~~
    test_leap.zig:7:43: note: called from here
        comptime try testing.expect(!leap.leap(2015));
                                     ~~~~~~~~~^~~~~~